version:  "3.0"

services:
    db:
        image: mysql:5.7
        command: ["--default-authentication-plugin=mysql_native_password"]
        volumes:
            - ./data/sql:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: database
            MYSQL_USER: dbuser
            MYSQL_PASSWORD: dbpassword

    app:
        build:
            context: .
            args:
                APP_NAME: 'myapp'
                COMPOSER_OPTION: ''
        depends_on:
            - db
        volumes:
            - ./:/www:cached
            - ignore:/www/app/vendor    # ignore vendor folder
            - ignore:/www/app/var/cache # ignore var cache folder
            - ignore:/www/app/var/logs  # ignore var logs folder
        restart: always

    node:
        build:
            context: .
            dockerfile: docker/node/Dockerfile
        volumes:
#            - ./public/build:/www/app/public/build
            - ./:/www
        command: bash -c "yarn install && yarn encore dev --watch"
    
    front:
        build:
            context: .
            dockerfile: ./docker/front/Dockerfile
        ports:
            - "80:80"
        links:
            - "app:app"
        volumes:
            - ./app/public/build:/www/app/public/build
        restart: always
        environment:
            HOST_PREFIX: dev
            
    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: password            

volumes:
    ignore: ~
    
    
    
